scan_frequency: 30m
memory_duration: 240h

sources:
  - name: vlans
    kind: static
    cidr:
      - "192.168.3.0/24"
      - "192.168.4.0/24"
  - name: pingable
    kind: ping_filter
    sources:
      - vlans
  - name: nodeexporters
    kind: prom_exporter_filter
    sources:
      - pingable
    url: http://TBD:9100/metrics
    metric: node_uname_info
  - name: dsbox
    kind: prom_exporter_filter
    sources:
      - pingable
    url: http://TBD:3000/metrics
    metric: dsbox_info
  - name: public_snmp
    kind: snmp_filter
    sources:
      - pingable
    community: "public"
    version: v2c
targets:
  - name: nodeexporter
    sources: 
      - nodeexporters
    reports:
      - name: probe
        template_file: probe-nodeexporter.yaml.tmpl
        namespace: "observability"
    publishers:
      - kind: log
        report: probe
  - name: dsbox
    sources: 
      - dsbox
    reports:
      - name: probe
        template_file: probe-dsbox.yaml.tmpl
        namespace: "observability"
    publishers:
      - kind: log
        report: probe
#  - name: snmp
#    sources: 
#      - public_snmp
#    reports:
#      - name: probe
#        template_file: probe-snmpexporter.yaml.tmpl
#        namespace: "observability"
#        community: "public"
#        version: v2c
#    publishers:
#      - kind: log
#        report: probe
