scan_frequency: 60m
memory_duration: 240h

sources:
  - name: management_vlans
    kind: static
    cidr:
      - "192.168.3.0/24"
  - name: management_pingable
    kind: ping
    sources:
      - management_vlans
  - name: nodeexporters
    kind: http
    sources:
      - management_pingable
    url: "http://TBD:9100/metrics"
    metric: "node_cpu_seconds_total"
  - name: public_snmp
    kind: snmp
    sources:
      - management_pingable
    community: "public"
    version: v2c
targets:
  - name: nodeexporter
    sources: 
      - nodeexporters
    reports:
      - name: probe
        template_file: probe-nodeexporter.yaml.tmpl
        namespace: "observability"
    publishers:
      - kind: log
        report: probe
  - name: snmp
    sources: 
      - public_snmp
    reports:
      - name: probe
        template_file: probe-snmpexporter.yaml.tmpl
        namespace: "observability"
        community: "public"
        version: v2c
    publishers:
      - kind: log
        report: probe
